Use django.contrib.staticfiles.storage from Django==3.2.12
to workaround

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 2819:
grappelli/tinymce/jscripts/tiny_mce/plugins/spellchecker/editor_plugin.js

Fixes KIWI-TCMS-HK,
https://sentry.io/organizations/kiwitcms/issues/2981977915

There have been changes in how ManifestStaticFilesStorage works in
Django 4.0 which are not working well for the moment, see:
https://docs.djangoproject.com/en/4.0/releases/4.0/#django-contrib-staticfiles